name: Docker Build

on:
  push:
    branches:
      - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: |
          docker build \
          -t arthaflow-backend \
          ./backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t arthaflow-frontend \
          ./frontend

      - name: Validate Docker Compose
        run: docker compose config